// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http "github.com/go-kit/kit/transport/http"
	endpoint "github.com/k4lii/golang_microservices/accounts/pkg/endpoint"
	http1 "net/http"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := http1.NewServeMux()
	makeCreateAccountHandler(m, endpoints, options["CreateAccount"])
	makeDeleteAccountHandler(m, endpoints, options["DeleteAccount"])
	makeGetSelfAccountHandler(m, endpoints, options["GetSelfAccount"])
	makeUpdateAccountHandler(m, endpoints, options["UpdateAccount"])
	makeReadOtherAccountHandler(m, endpoints, options["ReadOtherAccount"])
	makeLoginHandler(m, endpoints, options["Login"])
	makeAddToBalanceHandler(m, endpoints, options["AddToBalance"])
	makeSusbstractToBalanceHandler(m, endpoints, options["SusbstractToBalance"])
	return m
}
