// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	endpoint "github.com/go-kit/kit/endpoint"
	service "github.com/k4lii/golang_microservices/messages/pkg/service"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	AddMessageEndpoint endpoint.Endpoint
	GetMessageEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.MessagesService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		AddMessageEndpoint: MakeAddMessageEndpoint(s),
		GetMessageEndpoint: MakeGetMessageEndpoint(s),
	}
	for _, m := range mdw["AddMessage"] {
		eps.AddMessageEndpoint = m(eps.AddMessageEndpoint)
	}
	for _, m := range mdw["GetMessage"] {
		eps.GetMessageEndpoint = m(eps.GetMessageEndpoint)
	}
	return eps
}
