// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package service

import (
	endpoint1 "github.com/go-kit/kit/endpoint"
	log "github.com/go-kit/kit/log"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	http "github.com/go-kit/kit/transport/http"
	endpoint "github.com/k4lii/golang_microservices/transactions/pkg/endpoint"
	http1 "github.com/k4lii/golang_microservices/transactions/pkg/http"
	service "github.com/k4lii/golang_microservices/transactions/pkg/service"
	group "github.com/oklog/oklog/pkg/group"
	opentracinggo "github.com/opentracing/opentracing-go"
)

func createService(endpoints endpoint.Endpoints) (g *group.Group) {
	g = &group.Group{}
	initHttpHandler(endpoints, g)
	return g
}
func defaultHttpOptions(logger log.Logger, tracer opentracinggo.Tracer) map[string][]http.ServerOption {
	options := map[string][]http.ServerOption{
		"ListOwnOffers": {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "ListOwnOffers", logger))},
		"MakeOffer":     {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "MakeOffer", logger))},
		"ManageOffer":   {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "ManageOffer", logger))},
	}
	return options
}
func addDefaultEndpointMiddleware(logger log.Logger, duration *prometheus.Summary, mw map[string][]endpoint1.Middleware) {
	mw["MakeOffer"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "MakeOffer")), endpoint.InstrumentingMiddleware(duration.With("method", "MakeOffer"))}
	mw["ManageOffer"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "ManageOffer")), endpoint.InstrumentingMiddleware(duration.With("method", "ManageOffer"))}
	mw["ListOwnOffers"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "ListOwnOffers")), endpoint.InstrumentingMiddleware(duration.With("method", "ListOwnOffers"))}
}
func addDefaultServiceMiddleware(logger log.Logger, mw []service.Middleware) []service.Middleware {
	return append(mw, service.LoggingMiddleware(logger))
}
func addEndpointMiddlewareToAllMethods(mw map[string][]endpoint1.Middleware, m endpoint1.Middleware) {
	methods := []string{"MakeOffer", "ManageOffer", "ListOwnOffers"}
	for _, v := range methods {
		mw[v] = append(mw[v], m)
	}
}
