// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http "github.com/go-kit/kit/transport/http"
	endpoint "github.com/k4lii/golang_microservices/transactions/pkg/endpoint"
	http1 "net/http"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := http1.NewServeMux()
	makeMakeOfferHandler(m, endpoints, options["MakeOffer"])
	makeManageOfferHandler(m, endpoints, options["ManageOffer"])
	makeListOwnOffersHandler(m, endpoints, options["ListOwnOffers"])
	return m
}
